image: python:3.14

default:
  tags:
    - myrunner

stages:
  - testing
  - build
  - deploy

before_script:
  - python --version
  - python -m pip install --upgrade pip
  - pip install poetry
  - poetry install

lint:
  stage: testing
  script:
    - make lint

test:
  stage: testing
  script:
    - make coverage

build-job:
  stage: build
  script:
    - echo "TODO building."

deploy-job:
  stage: deploy
  script:
    - echo "TODO deploying."
