# Generated by Django 6.0.7 on 2026-09-23 10:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('published_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год издания')),
                ('is_pending', models.BooleanField(default=False, help_text='Книга заведена быстрой формой из дневника: заполнены только название и автор.', verbose_name='Требует дозаполнения')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_books', to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='bookshelf_app.author')),
                ('genres', models.ManyToManyField(blank=True, related_name='books', to='bookshelf_app.genre')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Хочу прочитать'), ('reading', 'Читаю'), ('read', 'Прочитано'), ('abandoned', 'Брошено')], default='planned', max_length=10, verbose_name='Статус')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='Начато')),
                ('finished_at', models.DateField(blank=True, null=True, verbose_name='Закончено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено в дневник')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='bookshelf_app.book', verbose_name='Книга')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL, verbose_name='Читатель')),
            ],
            options={
                'verbose_name': 'запись дневника',
                'verbose_name_plural': 'записи дневника',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookshelf_app.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Читатель')),
            ],
        ),
    ]
