# Generated by Django 6.0.7 on 2026-09-24 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Когда удалено"
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто удалил",
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удалено"),
        ),
        migrations.AddField(
            model_name="book",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Когда удалено"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто удалил",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удалено"),
        ),
        migrations.AddField(
            model_name="readingentry",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Когда удалено"
            ),
        ),
        migrations.AddField(
            model_name="readingentry",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто удалил",
            ),
        ),
        migrations.AddField(
            model_name="readingentry",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удалено"),
        ),
        migrations.AddField(
            model_name="review",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Когда удалено"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто удалил",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удалено"),
        ),
        migrations.AlterField(
            model_name="book",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="added_books",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто добавил",
            ),
        ),
    ]
