# Generated by Django 6.0.7 on 2026-09-25 06:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf_app", "0002_soft_delete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="books",
                to="bookshelf_app.author",
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="genres",
            field=models.ManyToManyField(
                blank=True,
                related_name="books",
                to="bookshelf_app.genre",
                verbose_name="Жанры",
            ),
        ),
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Создание"),
                            ("updated", "Изменение"),
                            ("deleted", "Удаление"),
                            ("restored", "Восстановление"),
                        ],
                        max_length=10,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[("book", "Книга"), ("author", "Автор")],
                        max_length=10,
                        verbose_name="Тип объекта",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveBigIntegerField(verbose_name="id объекта"),
                ),
                (
                    "object_repr",
                    models.CharField(max_length=200, verbose_name="Объект"),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{поле: {"old": старое значение, "new": новое}}',
                        verbose_name="Изменения",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Когда",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто",
                    ),
                ),
            ],
            options={
                "verbose_name": "событие журнала",
                "verbose_name_plural": "журнал событий",
                "ordering": ("-created_at", "-pk"),
            },
        ),
    ]
